spring.application.name=plateforme-immobiliere
# ===================================================================
# Configuration de la base de données PostgreSQL en local
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/plateforme_immobiliere_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# Configuration JPA / Hibernate
# ===================================================================
# NOTE : "create" pour la première connexion afin de créer les tables, puis passer à "update"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# Port du serveur Spring Boot
# ===================================================================
server.port=8081

#====================================================================
# Configuration JWT (Clé 256 bits codée en Base64)
# Generer avec la commande linux 'openssl rand -hex 32'

#====================================================================
application.security.jwt.secret-key=0774bd65a8828bdc2429e85dfc4d8233d6ff10cdcace1074a8fddee44f49c23b
application.security.jwt.expiration=86400000